name: ui-preview-deploy-action

description: Deploys Storybooks of Yandex Cloud UI packages to S3

inputs:
  project:
    description: ID of your project
    required: true
  github-token:
    description: PAT of a GitHub user which maintains PR's deploy comment
    required: true
  s3-key-id:
    description: S3 key ID
    required: true
  s3-secret-key:
    description: S3 secret key
    required: true

runs:
  using: composite
  steps:
  - name: Download Artifacts
    uses: dawidd6/action-download-artifact@v2
    with:
      workflow: ${{ github.event.workflow_run.workflow_id }}
      run_id: ${{ github.event.workflow_run.id }}
  - name: Extract PR Number
    id: pr
    run: echo "::set-output name=id::$(<pr/pr-id.txt)"
    shell: bash
  - name: Upload to S3
    uses: yandex-cloud/ui-preview-upload-to-s3-action@main
    with:
      src-path: static
      dest-path: /${{ inputs.project }}/pulls/${{ steps.pr.outputs.id }}/
      s3-key-id: ${{ secrets.STORYBOOK_S3_KEY_ID }}
      s3-secret-key: ${{ secrets.STORYBOOK_S3_SECRET_KEY }}
  - name: Create Comment
    uses: marocchino/sticky-pull-request-comment@v2
    with:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      number: ${{ steps.pr.outputs.id }}
      message: '[Preview](https://preview.yandexcloud.dev/${{ inputs.project }}/${{ steps.pr.outputs.id }}/) is ready.'
