name: ui-preview-deploy-action

description: Deploys Storybooks of Yandex Cloud UI packages to S3

inputs:
  project:
    description: ID of your project
    required: true
  github-token:
    description: PAT of a GitHub user which maintains PR's deploy comment
    required: true
  s3-key-id:
    description: S3 key ID
    required: true
  s3-secret-key:
    description: S3 secret key
    required: true

runs:
  using: composite
  steps:
  - name: Download Artifacts
    uses: dawidd6/action-download-artifact@v2
    with:
      workflow: ${{ github.event.workflow_run.workflow_id }}
      run_id: ${{ github.event.workflow_run.id }}
  - name: Extract PR Number
    id: pr
    run: echo "::set-output name=id::$(<pr/pr-id.txt)"
    shell: bash
  - name: Upload to S3
    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.s3-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.s3-secret-key }}
      AWS_DEFAULT_REGION: ru-central1
      AWS_EC2_METADATA_DISABLED: true
    run: aws s3 cp ./static s3://storybook-static/${{ inputs.project }}/pulls/${{ steps.pr.outputs.id }}/ --endpoint-url=https://storage.yandexcloud.net --recursive
    shell: bash
  - name: Create Comment
    uses: marocchino/sticky-pull-request-comment@v2
    with:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      number: ${{ steps.pr.outputs.id }}
      message: '[Preview](https://preview.yandexcloud.dev/${{ inputs.project }}/${{ steps.pr.outputs.id }}/) is ready.'
